Repository elastic/rally-teams, pull requests merged in 2019-10, with the labels that each got.

#32 Parameterize OS name + CPU arch in download URL.
  cars/v1/default_distro/config.ini
Labels: bug

#33 Remove option to enable direct buffer pooling
  cars/v1/vanilla/templates/config/jvm.options
Labels: enhancement

#34 Use node name to specify initial master nodes
  cars/v1/vanilla/templates/config/elasticsearch.yml
Labels: backport pending, bug
