Repository elastic/rally-teams, pull requests merged in 2020-01, with the labels that each got.

#37 Add flag to indicate if a bundled JDK is available
  cars/v1/vanilla/config.ini
Labels: enhancement

#38 Reference config properties specific to the system
  cars/v1/default_distro/config.ini
  cars/v1/vanilla/config.ini
Labels: enhancement

#39 Repository s3 and gcs keystore
  plugins/v1/repository_gcs/README.md
  plugins/v1/repository_gcs/plugin.py
  plugins/v1/repository_s3/README.md
  plugins/v1/repository_s3/plugin.py
Labels: enhancement

#41 Configurable x-pack-security settings (#40)
  cars/v1/x_pack/README.md
  cars/v1/x_pack/base/config.py
Labels: backport

#42 Fix typos in README and error message ...
  plugins/v1/repository_s3/README.md
  plugins/v1/repository_s3/plugin.py
Labels: backport pending, bug
